### ISSUE TITLE
Error running annotation step

### ISSUE THREAD

**Issue by qtrinh** [RabadanLab/TOBI#2]
Hi,
  I am trying out TOBI but get the following error on the annotation step.  Could someone please tell me how to get around this error?

Thanks

TOBIvaf.py --inputdir input/vcf --output output --steps A --ref $REF --cluster hpc --snpeff $SNPEFF --dbnsfp $dbNSFP
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/.mounts/labs/public/softwares/TOBI-master/TOBIvaf.py", line 195, in annotate
    args.annovcf = args.annovcf.replace("\n","")
AttributeError: 'NoneType' object has no attribute 'replace'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/.mounts/labs/public/softwares/TOBI-master/TOBIvaf.py", line 195, in annotate
    args.annovcf = args.annovcf.replace("\n","")
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by cjmadubata** [comment]
Hello,
This error suggests that no annotating VCFs were supplied to TOBI in the config file. A set of annotating VCFs is required to run TOBI, as stated in the readme and demonstrated in the example config file.

Please try pulling the latest version of TOBI, then running it using annotating VCFs such as COSMIC's VCF Files for coding mutations (found at http://grch37-cancer.sanger.ac.uk/cosmic/download via SFTP Download: /files/grch37/cosmic/v77/VCF/CosmicCodingMuts.vcf.gz).

If you continue having errors, please include the error message, command, and config file in your message to us.
